# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
lune = "lune-org/lune@0.8.9"
darklua = "seaofvoices/darklua@0.14.0"
# rojo = "rojo-rbx/rojo@6.2.0"